version: '3.7'
services:
  app:
    container_name: LEA-2.0-WEB
    build:
      context: .
    ports:
      - ${APP_PORT}:80
    depends_on: 
      - db
    volumes:
      # CURRENT__WORKING_DIRECTORY:CONTAINER_PATH_TO_WORKING_DIRECTORY
      - .:/var/www/html
  db:
    container_name: LEA-2.0-DB
    image: mariadb
    restart: always
    ports: 
      - ${DB_PORT}:3306
    volumes:
      - mysql-lea2.0:/var/lib/mysql
    environment:
      TZ: "Europe/Warsaw"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
  cache:
    image: redis:alpine
    volumes: 
      - cachedata:/data    
  phpmyadmin:
    container_name: LEA-2.0-DBMS
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
volumes:
  mysql-lea2.0:
  cachedata: