HomepageModule:
    prefix: "/"
    endpoints:
        homepage:
            url: "/"
            controller: HomepageController
            methods:
                - GET

#modules
OfferModule:
    prefix: "/offers"
    endpoints:
        by-id:
            url: "/offers/{id}"
            controller: OfferController
        collection:
            url: "/offers"
            controller: OfferCollectionController
        submit:
            url: "/offers/confirm"
            controller: OfferConfirmController

ContractorModule:
    prefix: "/contractors"
    endpoints:
        by-id:
            url: "/contractors/{id}"
            controller: ContractorController
        collection:
            url: "/contractors"
            controller: ContractorCollectionController
        library-administrative-division:
            url: "/contractors/libraries"
            controller: LibraryAdministrativeDivisionController
            params: ["postcode"]
        nutshell:
            url: "/contractors/nutshell"
            controller: ContractorNutshellCollectionController

CalendarModule:
    prefix: "/calendar"
    endpoints:
        event:
            url: "/calendar/events/{id}"
            controller: EventController
            allow: [user, admin]
        events:
            url: "/calendar/events"
            controller: EventCollectionController
        daily:
            url: "/calendar/daily"
            params: ["date"]
            controller: "DailyScheduleController"
        monthly:
            url: "/calendar/monthly"
            params: ["month", "year"]
            controller: "MonthlyScheduleController"

Security:
    prefix: "/security"
    endpoints:
        login:
            url: "/security/login"
            controller: LoginController
            allow: ['all']
        roles:
            url: "/security/roles"
            controller: RoleCollectionController
        role:
            url: "/security/roles/{id}"
            controller: RoleController
        users:
            url: "/security/users"
            controller: UserCollectionController
        user:
            url: "/security/users/{id}"
            controller: UserController