index:
  prefix: "/"
  endpoints:
    homepage:
      url: "/"
      controller: HomepageController
      methods:
        - GET

#modules
OfferModule:
  prefix: "/offers"
  endpoints:
    by-id:
      url: "/offers/{id}"
      controller: OfferController
    collection:
      url: "/offers"
      controller: OfferCollectionController
    submit:
      url: "/offers/confirm"
      controller: OfferConfirmController
