HomepageModule:
    prefix: "/"
    endpoints:
        homepage:
            url: "/"
            controller: HomepageController
            methods:
                - GET

#modules
OfferModule:
    prefix: "/offers"
    endpoints:
        by-id:
            url: "/offers/{id}"
            controller: OfferController
        collection:
            url: "/offers"
            controller: OfferCollectionController
        submit:
            url: "/offers/confirm"
            controller: OfferConfirmController

ContractorModule:
    prefix: "/contractors"
    endpoints:
        by-id:
            url: "/contractors/{id}"
            controller: ContractorController
        collection:
            url: "/contractors"
            controller: ContractorCollectionController
        library-administrative-division:
            url: "/contractors/libraries"
            controller: LibraryAdministrativeDivisionController
            params: ["postcode"]
        nutshell:
            url: "/contractors/nutshell"
            controller: ContractorNutshellCollectionController

CalendarModule:
    prefix: "/calendar"
    endpoints:
        event:
            url: "/calendar/events/{id}"
            controller: CalendarEventController
            allow: [user, admin]
        events:
            url: "/calendar/events"
            controller: CalendarEventCollectionController
        daily:
            url: "/calendar/daily"
            params: ["date"]
            controller: "DailyScheduleController"
        monthly:
            url: "/calendar/monthly"
            params: ["month", "year"]
            controller: "MonthlyScheduleController"

Security:
    prefix: "/security"
    endpoints:
        login:
            url: "/security/login"
            controller: LoginController
            allow: ['all']
        register:
            url: "/security/register"
            controller: RegisterController
            allow: ['admin']
        activate-account:
            url: "/security/account-activation"
            controller: AccountActivationController
            body-params: ['token', 'password']
            allow: ['all']
        email-resend:
            url: "/security/account-activation-email-resend"
            controller: AccountActivationEmailResendController
            params: ['email']
            allow: ['all']
        roles:
            url: "/security/roles"
            controller: RoleCollectionController
        role:
            url: "/security/roles/{id}"
            controller: RoleController
        role-hierarchy:
            url: "/security/role-hierarchy"
            controller: RoleHierarchyController
        users:
            url: "/security/users"
            controller: UserCollectionController
        user:
            url: "/security/users/{id}"
            controller: UserController
        users-subordinates:
            url: "/security/users/subordinates"
            controller: UserSubordinateController