index:
  prefix: "/"
  endpoints:
    homepage:
      url: "/"
      controller: HomepageController
      methods:
        - GET

#modules
OfferModule:
  prefix: "/offers"
  endpoints:
    by-id:
      url: "/offers/{id}"
      params:
        id: int
      controller: OfferController
      methods:
        - GET
        - POST
        - PUT
        - DELETE
    collection:
      url: "/offers"
      controller: OfferCollectionController
      methods:
        - GET
        - POST
    submit:
      url: "/offers/confirm"
      controller: OfferConfirm
